import type { Scholarship } from "@/lib/scholarships";

/**
 * Curated seed set of REAL, well-known, broadly-applicable U.S. scholarships
 * (docs/DATA_SOURCES.md). Amounts, deadlines, and competitiveness are approximate
 * and change year to year — this is a demonstrative starting set, not an
 * exhaustive or live directory, and the app says so. Sourced from public
 * scholarship listings. `competitiveness` reflects rough odds of winning (see
 * WIN_PROBABILITY in scholarships.ts), which is what drives expected value.
 */
export const SCHOLARSHIPS: Scholarship[] = [
  // --- Premier national, full-ride / large (elite odds) ---
  { id: "gates", name: "The Gates Scholarship", provider: "Bill & Melinda Gates Foundation", amount: 90000, renewable: true, deadline: "Sep 15", deadlineMonth: 9, competitiveness: "elite", field: "any", eligibility: ["HS senior", "Pell-eligible", "Minority students"], blurb: "Full cost of attendance not covered by other aid, for exceptional minority students with financial need.", url: "https://www.thegatesscholarship.org/" },
  { id: "questbridge", name: "QuestBridge National College Match", provider: "QuestBridge", amount: 250000, renewable: true, deadline: "Sep 26", deadlineMonth: 9, competitiveness: "elite", field: "any", eligibility: ["HS senior", "Low income", "High achieving"], blurb: "Matches high-achieving, low-income students to full four-year scholarships (often $250k+) at partner colleges.", url: "https://www.questbridge.org/high-school-students/national-college-match" },
  { id: "cooke-college", name: "Jack Kent Cooke College Scholarship", provider: "Jack Kent Cooke Foundation", amount: 220000, renewable: true, deadline: "Nov 12", deadlineMonth: 11, competitiveness: "elite", field: "any", eligibility: ["HS senior", "Financial need", "GPA 3.5+"], blurb: "Up to $55,000 a year — as much as ~$220,000 over four years — for high-achievers with financial need.", url: "https://www.jkcf.org/our-scholarships/jack-kent-cooke-college-scholarship-program/" },
  { id: "coca-cola", name: "Coca-Cola Scholars Program", provider: "Coca-Cola Foundation", amount: 20000, renewable: false, deadline: "Sep 30", deadlineMonth: 9, competitiveness: "elite", field: "any", eligibility: ["HS senior", "Leadership", "Service"], blurb: "150 awards a year (from 100,000+ applicants) for leadership, service, and academics.", url: "https://www.coca-colascholarsfoundation.org/apply/" },
  { id: "ron-brown", name: "Ron Brown Scholar Program", provider: "Ron Brown Scholar Fund", amount: 40000, renewable: true, deadline: "Dec 1", deadlineMonth: 12, competitiveness: "elite", field: "any", eligibility: ["Black students", "Leadership", "Service"], blurb: "$10,000/year for Black students with academic excellence, leadership, and community involvement.", url: "https://www.ronbrown.org/apply/" },
  { id: "cameron", name: "Cameron Impact Scholarship", provider: "Bryan Cameron Education Foundation", amount: 140000, renewable: true, deadline: "Sep 3", deadlineMonth: 9, competitiveness: "elite", field: "any", eligibility: ["HS senior", "Academic excellence", "Community impact"], blurb: "Four-year full-tuition award ($20,000–$60,000/year) for students who pair academics with community impact.", url: "https://www.cameronimpact.org/apply/" },
  { id: "stamps", name: "Stamps Scholarship", provider: "Stamps Scholars", amount: 160000, renewable: true, deadline: "Varies", deadlineMonth: null, competitiveness: "elite", field: "any", eligibility: ["HS senior", "Merit", "Partner colleges"], blurb: "Merit scholarships covering full cost of attendance at partner universities.", url: "https://www.stampsscholars.org/" },

  // --- Competitive national ---
  { id: "dell", name: "Dell Scholars Program", provider: "Michael & Susan Dell Foundation", amount: 20000, renewable: true, deadline: "Dec 1", deadlineMonth: 12, competitiveness: "competitive", field: "any", eligibility: ["HS senior", "Financial need", "College-readiness program"], blurb: "$20,000 plus support services for students who show grit and financial need.", url: "https://www.dellscholars.org/scholarship/" },
  { id: "elks-mvs", name: "Elks Most Valuable Student", provider: "Elks National Foundation", amount: 30000, renewable: true, deadline: "Nov 12", deadlineMonth: 11, competitiveness: "competitive", field: "any", eligibility: ["HS senior", "Leadership", "Financial need"], blurb: "500 four-year awards; top scholars receive $30,000 (others from $4,000), on merit, leadership, and need.", url: "https://www.elks.org/scholars/scholarships/mvs.cfm" },
  { id: "horatio-alger", name: "Horatio Alger National Scholarship", provider: "Horatio Alger Association", amount: 25000, renewable: false, deadline: "Oct 25", deadlineMonth: 10, competitiveness: "competitive", field: "any", eligibility: ["HS senior", "Overcame adversity", "Financial need"], blurb: "For students who have overcome significant adversity while maintaining strong grades.", url: "https://scholars.horatioalger.org/scholarships/" },
  { id: "ge-reagan", name: "GE-Reagan Foundation Scholarship", provider: "Ronald Reagan Presidential Foundation", amount: 40000, renewable: true, deadline: "Jan 4", deadlineMonth: 1, competitiveness: "competitive", field: "any", eligibility: ["HS senior", "Leadership", "Integrity"], blurb: "$10,000/year for students who demonstrate leadership, drive, integrity, and citizenship.", url: "https://www.reaganfoundation.org/education/ge-reagan-foundation-scholarship-program/" },
  { id: "jackie-robinson", name: "Jackie Robinson Foundation Scholarship", provider: "Jackie Robinson Foundation", amount: 30000, renewable: true, deadline: "Feb 15", deadlineMonth: 2, competitiveness: "competitive", field: "any", eligibility: ["Minority students", "Leadership", "Financial need"], blurb: "Up to $30,000 over four years plus mentoring for minority students with leadership potential.", url: "https://www.jackierobinson.org/apply/" },
  { id: "hagan", name: "Hagan Scholarship", provider: "Hagan Scholarship Foundation", amount: 48000, renewable: true, deadline: "Dec 1", deadlineMonth: 12, competitiveness: "competitive", field: "any", eligibility: ["Rural public HS", "Financial need", "Work history"], blurb: "Up to $48,000 for students from rural public high schools with demonstrated need.", url: "https://www.haganscholarship.org/apply" },
  { id: "foot-locker", name: "Foot Locker Scholar Athletes", provider: "Foot Locker Foundation", amount: 20000, renewable: false, deadline: "Jan 5", deadlineMonth: 1, competitiveness: "competitive", field: "any", eligibility: ["Student-athlete", "Leadership", "GPA 3.0+"], blurb: "For student-athletes who excel in sport, academics, and community leadership.", url: "https://www.footlockerscholarathletes.com/" },
  { id: "point", name: "Point Foundation Scholarship", provider: "Point Foundation", amount: 10000, renewable: true, deadline: "Jan 27", deadlineMonth: 1, competitiveness: "competitive", field: "any", eligibility: ["LGBTQ students", "Leadership", "Financial need"], blurb: "Scholarship and mentorship for LGBTQ students who show leadership and resilience.", url: "https://pointfoundation.org/scholarships/" },
  { id: "american-legion", name: "American Legion Oratorical Contest", provider: "The American Legion", amount: 25000, renewable: false, deadline: "Varies", deadlineMonth: null, competitiveness: "competitive", field: "any", eligibility: ["HS student", "Public speaking"], blurb: "Speech contest on the U.S. Constitution with up to $25,000 for national winners.", url: "https://www.legion.org/oratorical" },

  // --- Moderate national / field pools ---
  { id: "hsf", name: "Hispanic Scholarship Fund", provider: "Hispanic Scholarship Fund", amount: 5000, renewable: false, deadline: "Feb 15", deadlineMonth: 2, competitiveness: "moderate", field: "any", eligibility: ["Hispanic heritage", "GPA 3.0+"], blurb: "$500–$5,000 awards for students of Hispanic heritage, plus career support.", url: "https://www.hsf.net/scholarship" },
  { id: "prudential", name: "Prudential Emerging Visionaries", provider: "Prudential Financial", amount: 15000, renewable: false, deadline: "Nov 4", deadlineMonth: 11, competitiveness: "moderate", field: "any", eligibility: ["Ages 14-18", "Community impact"], blurb: "For young people creating financial or societal change in their communities.", url: "https://www.prudential.com/links/about/emergingvisionaries" },
  { id: "comcast", name: "Comcast Leaders & Achievers", provider: "Comcast NBCUniversal Foundation", amount: 2500, renewable: false, deadline: "Dec 6", deadlineMonth: 12, competitiveness: "moderate", field: "any", eligibility: ["HS senior", "Service", "Leadership"], blurb: "$2,500 for seniors who demonstrate community service and leadership.", url: "https://corporate.comcast.com/impact/education/leaders-and-achievers-scholarship-program" },
  { id: "vfw-vod", name: "VFW Voice of Democracy", provider: "Veterans of Foreign Wars", amount: 35000, renewable: false, deadline: "Oct 31", deadlineMonth: 10, competitiveness: "moderate", field: "any", eligibility: ["Grades 9-12", "Audio essay"], blurb: "Audio-essay contest on a patriotic theme; top prize up to $35,000.", url: "https://www.vfw.org/community/youth-and-education/youth-scholarships/voice-of-democracy" },
  { id: "dr-pepper", name: "Dr Pepper Tuition Giveaway", provider: "Dr Pepper", amount: 100000, renewable: false, deadline: "Sep 30", deadlineMonth: 9, competitiveness: "competitive", field: "any", eligibility: ["Ages 18-24", "Video pitch"], blurb: "Pitch your goals on video for a shot at one of three $100,000 tuition prizes (plus $25,000 and $2,500 awards).", url: "https://www.drpeppertuition.com/" },
  { id: "taco-bell", name: "Taco Bell Live Más Scholarship", provider: "Taco Bell Foundation", amount: 25000, renewable: false, deadline: "Jan 12", deadlineMonth: 1, competitiveness: "moderate", field: "any", eligibility: ["Ages 16-26", "Video, no GPA"], blurb: "Passion-driven video application — no essay or transcript required.", url: "https://www.livemasscholarship.com/" },
  { id: "scholarship-america", name: "Scholarship America Dream Award", provider: "Scholarship America", amount: 15000, renewable: true, deadline: "Feb 20", deadlineMonth: 2, competitiveness: "moderate", field: "any", eligibility: ["Past first year", "Financial need"], blurb: "Renewable, increasing awards for students beyond their first year of college.", url: "https://scholarshipamerica.org/students/browse-scholarships/dream-award/" },
  { id: "nshss-stem", name: "NSHSS STEM Scholarship", provider: "National Society of High School Scholars", amount: 2000, renewable: false, deadline: "Varies", deadlineMonth: null, competitiveness: "moderate", field: "stem", eligibility: ["STEM-focused", "NSHSS member"], blurb: "Awards for high-achieving students pursuing science, tech, engineering, or math.", url: "https://www.nshss.org/scholarships/" },

  // --- STEM ---
  { id: "regeneron-sts", name: "Regeneron Science Talent Search", provider: "Society for Science", amount: 250000, renewable: false, deadline: "Nov 8", deadlineMonth: 11, competitiveness: "elite", field: "stem", eligibility: ["HS senior", "Original research"], blurb: "The premier science research competition for high school seniors.", url: "https://www.societyforscience.org/regeneron-sts/" },
  { id: "davidson", name: "Davidson Fellows Scholarship", provider: "Davidson Institute", amount: 100000, renewable: false, deadline: "Feb 12", deadlineMonth: 2, competitiveness: "elite", field: "stem", eligibility: ["Under 18", "Significant project"], blurb: "$25,000–$100,000 for extraordinary STEM, literature, or music projects.", url: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/" },
  { id: "amazon-fe", name: "Amazon Future Engineer Scholarship", provider: "Amazon", amount: 40000, renewable: true, deadline: "Jan 18", deadlineMonth: 1, competitiveness: "competitive", field: "stem", eligibility: ["CS-bound", "Financial need"], blurb: "$40,000 plus a paid internship for students pursuing computer science.", url: "https://www.amazonfutureengineer.com/scholarships" },
  { id: "google-gen", name: "Generation Google Scholarship", provider: "Google", amount: 10000, renewable: false, deadline: "Dec 1", deadlineMonth: 12, competitiveness: "competitive", field: "stem", eligibility: ["CS/tech major", "Underrepresented in tech"], blurb: "$10,000 for students in computing from historically underrepresented groups.", url: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship/" },
  { id: "swe", name: "Society of Women Engineers Scholarship", provider: "SWE", amount: 16000, renewable: false, deadline: "Feb 15", deadlineMonth: 2, competitiveness: "moderate", field: "stem", eligibility: ["Women", "Engineering/CS"], blurb: "$1,000–$16,000 awards for women pursuing engineering and computing.", url: "https://swe.org/scholarships/" },
  { id: "microsoft", name: "Microsoft Tuition Scholarship", provider: "Microsoft", amount: 12000, renewable: false, deadline: "Jan 31", deadlineMonth: 1, competitiveness: "competitive", field: "stem", eligibility: ["CS/STEM major", "Passion for tech"], blurb: "Partial to full tuition for students studying computer science or STEM.", url: "https://www.microsoft.com/en-us/diversity/programs/microsoft-scholarship-program" },
  { id: "sae", name: "SAE Engineering Scholarships", provider: "SAE International", amount: 5000, renewable: false, deadline: "Varies", deadlineMonth: null, competitiveness: "moderate", field: "stem", eligibility: ["Engineering-bound", "Strong math/science"], blurb: "A range of awards for students entering accredited engineering programs.", url: "https://www.sae.org/participate/scholarships" },

  // --- Business / finance ---
  { id: "naba", name: "NABA National Scholarship", provider: "National Association of Black Accountants", amount: 6000, renewable: false, deadline: "Jan 31", deadlineMonth: 1, competitiveness: "moderate", field: "business", eligibility: ["Business/accounting", "NABA member"], blurb: "For students pursuing accounting, finance, or business, with leadership potential.", url: "https://nabainc.org/scholarships/" },
  { id: "zonta-klausman", name: "Jane M. Klausman Women in Business", provider: "Zonta International", amount: 10000, renewable: false, deadline: "Jul 1", deadlineMonth: 7, competitiveness: "moderate", field: "business", eligibility: ["Women", "Business major"], blurb: "$10,000 international awards for women pursuing business degrees with outstanding potential.", url: "https://www.zonta.org/Web/Education_and_Scholarships/Zonta_International_Programs/Jane_M_Klausman_Women_in_Business_Scholarship/" },
  { id: "deca", name: "DECA Scholarships", provider: "DECA Inc.", amount: 5000, renewable: false, deadline: "Jan 17", deadlineMonth: 1, competitiveness: "moderate", field: "business", eligibility: ["DECA member", "Business/marketing"], blurb: "Awards for DECA members heading into business, marketing, or entrepreneurship.", url: "https://www.deca.org/scholarships/" },
  { id: "fbla", name: "FBLA National Scholarships", provider: "Future Business Leaders of America", amount: 5000, renewable: false, deadline: "Varies", deadlineMonth: null, competitiveness: "moderate", field: "business", eligibility: ["FBLA member", "Business-bound"], blurb: "Merit awards for FBLA members pursuing business education.", url: "https://www.fbla.org/fbla/scholarships/" },
  { id: "aicpa", name: "AICPA Accounting Scholarship", provider: "AICPA Foundation", amount: 10000, renewable: false, deadline: "Mar 1", deadlineMonth: 3, competitiveness: "competitive", field: "business", eligibility: ["Accounting major", "GPA 3.0+"], blurb: "For students committed to earning an accounting degree and CPA license.", url: "https://www.thiswaytocpa.com/education/scholarship-search/" },

  // --- Healthcare ---
  { id: "tylenol", name: "Tylenol Future Care Scholarship", provider: "Tylenol", amount: 10000, renewable: false, deadline: "Jun 26", deadlineMonth: 6, competitiveness: "moderate", field: "healthcare", eligibility: ["Healthcare-bound", "GPA 2.5+"], blurb: "For students pursuing careers in medicine, nursing, or public health.", url: "https://www.tylenol.com/tylenol-future-care-scholarship" },
  { id: "aacn", name: "AfterCollege–AACN Nursing Scholarship", provider: "AfterCollege & AACN", amount: 2500, renewable: false, deadline: "Rolling", deadlineMonth: null, competitiveness: "moderate", field: "healthcare", eligibility: ["Nursing student", "GPA 3.25+"], blurb: "Quarterly $2,500 awards for students in nursing programs.", url: "https://www.aftercollege.com/scholarships/" },
  { id: "nhsc", name: "NHSC Scholarship Program", provider: "Health Resources & Services Admin.", amount: 120000, renewable: true, deadline: "Apr 30", deadlineMonth: 4, competitiveness: "competitive", field: "healthcare", eligibility: ["Primary-care track", "Service commitment"], blurb: "Full tuition plus stipend in exchange for service in underserved areas.", url: "https://nhsc.hrsa.gov/scholarships" },

  // --- Broad / easy odds (great for building momentum) ---
  { id: "burger-king", name: "Burger King Scholars Program", provider: "BURGER KING Foundation", amount: 2000, renewable: false, deadline: "Dec 15", deadlineMonth: 12, competitiveness: "broad", field: "any", eligibility: ["HS senior", "GPA 2.5+", "Many awards"], blurb: "Thousands of $1,000–$2,000 awards for graduating seniors (a rare few reach $60,000).", url: "https://www.bkscholars.saff.org/saff/" },
  { id: "gen-kelly", name: "Gen & Kelly Tanabe Scholarship", provider: "Gen and Kelly Tanabe", amount: 1000, renewable: false, deadline: "Jul 31", deadlineMonth: 7, competitiveness: "broad", field: "any", eligibility: ["Grades 9-college", "Short essay"], blurb: "Merit-based award open to virtually all students with a quick application.", url: "https://www.genkellyscholarship.com/" },
  { id: "dosomething", name: "DoSomething.org Scholarships", provider: "DoSomething.org", amount: 5000, renewable: false, deadline: "Rolling", deadlineMonth: null, competitiveness: "moderate", field: "any", eligibility: ["Any student", "Take action, no GPA"], blurb: "No-essay scholarships for joining volunteer and social-change campaigns.", url: "https://www.dosomething.org/us/scholarships" },
  { id: "bold", name: "Bold.org No-Essay Scholarship", provider: "Bold.org", amount: 1500, renewable: false, deadline: "Monthly", deadlineMonth: null, competitiveness: "moderate", field: "any", eligibility: ["Any student", "No essay"], blurb: "Recurring no-essay award — create a profile and get automatically entered.", url: "https://bold.org/scholarships/no-essay-scholarship/" },

  // --- Lottery-style (big number, terrible odds — teaches the yield lesson) ---
  { id: "niche-50k", name: "Niche $50,000 No-Essay Scholarship", provider: "Niche", amount: 50000, renewable: false, deadline: "Monthly", deadlineMonth: null, competitiveness: "lottery", field: "any", eligibility: ["Any student", "Register to enter"], blurb: "One winner drawn from a huge pool — huge payout, lottery odds.", url: "https://www.niche.com/colleges/scholarships/50k-no-essay-scholarship/" },
  { id: "sallie-mae", name: "Sallie Mae $2,000 Scholarship", provider: "Sallie Mae", amount: 2000, renewable: false, deadline: "Monthly", deadlineMonth: null, competitiveness: "lottery", field: "any", eligibility: ["Any student", "No essay"], blurb: "Monthly sweepstakes-style drawing; quick entry, low odds.", url: "https://www.salliemae.com/scholarships/2k-scholarship/" },
  { id: "nitro", name: "Nitro College Scholarship", provider: "Nitro", amount: 2000, renewable: false, deadline: "Monthly", deadlineMonth: null, competitiveness: "lottery", field: "any", eligibility: ["Any student", "No essay"], blurb: "No-essay monthly drawing — fast to enter, long odds.", url: "https://www.nitrocollege.com/scholarships/nitro-1000-scholarship" },
];
